"""empty message

Revision ID: 004e6ab34938
Revises: 7fe285cb6927
Create Date: 2022-06-29 15:55:37.264330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004e6ab34938'
down_revision = '7fe285cb6927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('taxonomy_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('zip_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('taxonomy_id', name='events_pkey')
    )
    # ### end Alembic commands ###
