"""empty message

Revision ID: 258fb5ed752b
Revises: 557c04edcbc9
Create Date: 2022-06-26 23:39:19.127973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258fb5ed752b'
down_revision = '557c04edcbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zipcode', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zipcode')
    # ### end Alembic commands ###
